version: '3.4'

services:
  freakyfashionservices.basket:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesbasket
    build:
      context: .
      dockerfile: FreakyFashionServices.Basket/Dockerfile

  freakyfashionservices.catalog:
    image: ${DOCKER_REGISTRY-}freakyfashionservicescatalog
    build:
      context: .
      dockerfile: FreakyFashionServices.Catalog/Dockerfile

  redis:
    image: redis

  ms-sql-server:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Testing1122"
    volumes:
        - C:\DockerVolumes\formssql:/var/opt/mssql/data
    ports:
      - "1433:1433"
