version: '3.4'

services:  
  ms-sql-server:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Testing1122"
    volumes:
        - C:\DockerVolumes\formssql:/var/opt/mssql/data
    ports:
      - "1433:1433"
  freakyfashionservices.catalog:
    container_name: freakyfashionContainer
    image: freakyfashion:latest
    build: .
    environment: 
        DBServer: "ms-sql-server"
    ports:
      - "8080:80"
