version: '3.4'

services:
  freakyfashionservices.basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  freakyfashionservices.catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashionservices.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashionservices.productprice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashionservices.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

